name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    branches: [master]
    types: [opened]


jobs:
    check_for_first_interaction:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: 'Welcome to the community 🎉, folks like you make Open Source meaningful. Firstly, thanks a lot for taking the time to go through the COC and CG and creating the issue according to the template. Hopefully, you have a good time over here. We will review your issue soon and take the necessary steps'
                  pr-message: 'Welcome to the community 🎉, folks like you fuel Open Source. Thanks for making your first PR  Hope it follows CONTRIBUTING.md. We will review your PR soon, thanks for your time'
