import { AS_FAMILY } from './IhrApi'

const DEFAULT_MIN_NPROBES = 10
const DEFAULT_MIN_DEVIATION = 150
const DEFAULT_MIN_DIFFMEDIAN = 15
const DEFAULT_MAX_DIFFMEDIAN = 300
const DEFAULT_AS_FAMILY = AS_FAMILY.v4

export {
  DEFAULT_MIN_NPROBES,
  DEFAULT_MIN_DEVIATION,
  DEFAULT_MIN_DIFFMEDIAN,
  DEFAULT_MAX_DIFFMEDIAN,
  DEFAULT_AS_FAMILY
}
